---
- name: Prueba
  hosts: all
  become: true
  tasks:
    - name: Instalar docker
      apt:
        name: docker
        state: latest
        
    - name: Instalar docker-compose 
      apt:
        name: docker-compose
        state: latest
        
    - name: Instalar python3
      apt:
        name: python3
        state: latest
    
    - name: Crear directorio
      ansible.builtin.file:
        path: "/mnt/volumes/{{item}}"
        state: directory
        mode: '0777'
      with_items:   
         - 'db-data'
         - 'gitlab-config'
         - 'gitlab-data'
         - 'gitlab-logs'
         - 'influx-data'
         - 'jenkins'
         - 'registry-auth'
         - 'registry-data'
